### ISSUE TITLE
La nave pierde toda la vida de golpe al recibir el disparo de vision

### ISSUE THREAD

**Issue by DanielAlba96** [DavidGG1983/ProyectoGrupo#33]
Rama Daniel

**Comment by miguelms95** [comment]
Era problema genérico de los enemigos (Enemigo.java), pasaba también con el lanzallamas, pero ya está.

**Comment by miguelms95** [comment]
Era problema genérico de los enemigos (Enemigo.java), pasaba también con el lanzallamas, pero ya está.

**Comment by DanielAlba96** [comment]
El problema persiste en master

**Comment by DanielAlba96** [comment]
Si te quedas parado en el disparo de vision pierdes toda la vida de golpe. Solo pasa en el disparo de vision

**Comment by DanielAlba96** [comment]
Fixed, faltaba un if para comprobar si la nave era invulnerable en el metodo de las colisiones
